### ISSUE TITLE
React .tsx files support

### ISSUE THREAD

**Issue by tim-kuteev** [rafaelrenanpacheco/darcula-theme#1]
Are **.tsx** files planned to be supported?

**Comment by rafaelrenanpacheco** [comment]
Hello @tim-kuteev!

I usually add color themes for the languages and frameworks I work with, and React along with .tsx is not the case so far. If you wish to make a PR for .tsx syntax please take a look at the [contribution session](https://github.com/rafaelrenanpacheco/darcula-theme/blob/master/README.md#contribution), it's very simple to enhance this theme.

Best regards,
Rafael Pacheco.

**Comment by rafaelrenanpacheco** [comment]
Hello @tim-kuteev!

Version 1.9.0 now have TSX support.

Best regards,
Rafael Pacheco.

**Comment by tim-kuteev** [comment]
@rafaelrenanpacheco great news, thanks! I'll check it out.
