### ISSUE TITLE
Please add support for Lua

### ISSUE THREAD

**Issue by JasperMZP** [rafaelrenanpacheco/darcula-theme#14]

**Comment by rafaelrenanpacheco** [comment]
Hi @JasperMZP!

You are welcome to contribute with the Lua support, it is very simple to do so. Check our [contribution guide](https://github.com/rafaelrenanpacheco/darcula-theme#contribution) and also [other contributors PRs](https://github.com/rafaelrenanpacheco/darcula-theme/pulls?q=is%3Apr+is%3Aclosed) to understand how to write the Lua support :+1:
