### ISSUE TITLE
Undefined color token for js "class" keyword.

### ISSUE THREAD

**Issue by aitorfi** [rafaelrenanpacheco/darcula-theme#15]
# Undefined color token for js "class" keyword.

I've noticed the keyword "class" has no color token assigned to it in JavaScript (see image bellow). If this is a expected behavior I'll modify my user settings for the theme but in case it isn't I'll open a PR adding the scope so that it looks as in the image bellow.

**"Class" keyword with unmodified theme:**

![2023-07-08_11-41-20](https://github.com/rafaelrenanpacheco/darcula-theme/assets/64830228/7e3604f1-8f1f-484d-a853-13541208271a)

**"Class" keyword with modified theme:**

![2023-07-08_11-41-42](https://github.com/rafaelrenanpacheco/darcula-theme/assets/64830228/b9a72145-646b-4dad-bf89-1185f0b216dc)

**Comment by rafaelrenanpacheco** [comment]
Released as 1.11.1, thanks @aitorfi :tada:
