### ISSUE TITLE
log file support

### ISSUE THREAD

**Issue by long76** [rafaelrenanpacheco/darcula-theme#25]
After install log files not highlight anymore

Suggest you copy log highlight from https://github.com/emilast/vscode-logfile-highlighter

Thanks!

**Comment by rafaelrenanpacheco** [comment]
That is an extension and it seems current version of VS code don't need them anymore. If the .log highlights can be achieved with color theme tokens, feel free to open a PR following our [#Contribution](https://github.com/rafaelrenanpacheco/darcula-theme?tab=readme-ov-file#contribution) guideline :+1:
