### ISSUE TITLE
 Regarding some font color display errors, we hope to have them corrected

### ISSUE THREAD

**Issue by Poril** [rafaelrenanpacheco/darcula-theme#26]
![02a55df510e786747fb40a7d5f58aa1](https://github.com/rafaelrenanpacheco/darcula-theme/assets/93561419/205c17d7-8ac6-4250-867c-4672e1b704e5)

**Comment by rafaelrenanpacheco** [comment]
Hello @Poril!

You can submit a fix following this guideline: https://github.com/rafaelrenanpacheco/darcula-theme?tab=readme-ov-file#contribution

This theme does not officially support `.vue` extension, the tags you flagged probably have a different token code that are not handled by this theme, but you can add them on your PR.

:+1:
