### ISSUE TITLE
Support for Jinja templates

### ISSUE THREAD

**Issue by haimat** [rafaelrenanpacheco/darcula-theme#3]
Hey, thanks for this color theme, IMHO it is the best Darcula clone for VS Code out there.
Only thing I miss is support for Python Jinja templates.
Any chance you can include those too?

**Comment by rafaelrenanpacheco** [comment]
Thanks for the feedback @haimat!

I just add support for the programming languages I use. If you would like to contribute by adding support for this language, please take a look at the contribution guide: https://github.com/rafaelrenanpacheco/darcula-theme#contribution

It's very easy to enhance this theme.

Best regards.
