### ISSUE TITLE
Problems trying to add support for Vue to plugin.

### ISSUE THREAD

**Issue by ZiuChen** [rafaelrenanpacheco/darcula-theme#6]
Your plugin works great! It allows me to read code comfortably in VS Code.

As you can see, when I tried to add support for `Vue` to the plugin, I modified the color of the `Html` tag, but the tag content in the `Vue` file did not change color accordingly.

I have read the official documentation and sample, and there is no explanation for adding new languages. If possible, I would like to get your help, thank you very much!

![01](https://user-images.githubusercontent.com/64892985/150646980-d8bbcdc3-018d-41c6-ab18-3479cf291340.jpg)
![02](https://user-images.githubusercontent.com/64892985/150646979-25986c96-d6ae-4a85-8a49-062bd129d5ef.jpg)
![03](https://user-images.githubusercontent.com/64892985/150646978-9114bae7-d513-4824-bf00-4df21855240b.jpg)

**Comment by rafaelrenanpacheco** [comment]
Hello @ZiuChen!

Did you try this theme with a Vue plugin installed? Something like Vetur for example. I don't think vscode has native support for vue file components.
