### ISSUE TITLE
C++ and Go support

### ISSUE THREAD

**Issue by vlasopoulos** [rafaelrenanpacheco/darcula-theme#7]
First of all thanks a lot for the theme, it's the best out there.

Could I try and implement C++ (like Clion) and Go (like GoLand) support?
I have no experience with theming so I can't guarantee speed of implementation.

**Comment by rafaelrenanpacheco** [comment]
Hello @vlasopoulos 

I have no experience with Clion and GoLand IDE's, you may try to recreate them for this theme following this guideline and then opening a PR: https://github.com/rafaelrenanpacheco/darcula-theme#contribution

After you get used to it you will probably finish it in no time. Most key colors already exists in the `darcula.color-theme.json` file.

:+1:
